# Подготовка данных для обучения

In [1]:
import pandas as pd

data_path = 'data/credit_history_all.csv'

df = pd.read_csv(data_path)

In [2]:
del df['created_timestamp']
del df['event_timestamp']
del df['loan_id']
del df['zipcode']
del df['dob_ssn']

In [3]:
df.head()

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_amnt,loan_int_rate,loan_status,city,state,...,total_wages,credit_card_due,mortgage_due,student_loan_due,vehicle_loan_due,hard_pulls,missed_payments_2y,missed_payments_1y,missed_payments_6m,bankruptcies
0,52,69996,OWN,3.0,PERSONAL,12000,11.11,0,CUMMINGS,KS,...,9617849,7649,779433,28579,3583,0,0,0,0,0
1,61,10636,RENT,3.0,PERSONAL,4000,12.21,1,CRESSON,TX,...,38291019,5101,1877182,32008,20745,6,1,3,0,0
2,36,69000,RENT,0.0,MEDICAL,15600,10.99,0,PLAINVILLE,GA,...,23478174,4223,1142978,24020,11711,3,5,1,1,2
3,36,48686,RENT,21.0,MEDICAL,12000,13.99,0,CLINTON,NC,...,35505191,6993,592528,40529,17508,1,1,0,0,0
4,36,44000,RENT,4.0,DEBTCONSOLIDATION,8000,17.49,1,NASHVILLE,TN,...,571965786,1552,1786677,26664,19749,8,2,0,1,0

Для проверки в пайплайне с энкодером

In [4]:
X = df[df.columns.drop("loan_status")].copy()
y = df[["loan_status"]].copy()

In [5]:
columns = list(X.columns)
columns

['person_age',
 'person_income',
 'person_home_ownership',
 'person_emp_length',
 'loan_intent',
 'loan_amnt',
 'loan_int_rate',
 'city',
 'state',
 'location_type',
 'tax_returns_filed',
 'population',
 'total_wages',
 'credit_card_due',
 'mortgage_due',
 'student_loan_due',
 'vehicle_loan_due',
 'hard_pulls',
 'missed_payments_2y',
 'missed_payments_1y',
 'missed_payments_6m',
 'bankruptcies']

In [6]:
X = X.values
X

array([[52, 69996, 'OWN', ..., 0, 0, 0],
       [61, 10636, 'RENT', ..., 3, 0, 0],
       [36, 69000, 'RENT', ..., 1, 1, 2],
       ...,
       [24, 200000, 'MORTGAGE', ..., 0, 0, 0],
       [23, 74000, 'RENT', ..., 1, 0, 0],
       [23, 12996, 'OWN', ..., 0, 0, 2]], dtype=object)

In [7]:
y = y.values
y

array([[0],
       [1],
       [0],
       ...,
       [0],
       [1],
       [1]], dtype=int64)

In [8]:
len(y)

28638

# Инициализируем модели

In [9]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import OrdinalEncoder

class DTCModel(object):  
    
    def __init__(self):
        
        self.categorical_features = [
            "person_home_ownership",
            "loan_intent",
            "city",
            "state",
            "location_type",
        ]
        
        self.encoder = joblib.load("encoder.pkl")
        
        print("Encoder loaded")
        
        self.model = joblib.load("DTC.pkl")
        
        print("Model loaded")
        
        self.cm = {"tp": 0, "fp": 0, "tn": 0, "fn": 0}

        self.tries = 0
        self.success = 0
        self.value = 0
        

    def predict(self,X,features_names):

        df = pd.DataFrame(X, columns=features_names)
        
        df[self.categorical_features] = self.encoder.transform(df[self.categorical_features])
        df = df.reindex(sorted(df.columns), axis=1)
        
        predictions = self.model.predict(df)
        
        return predictions

    def send_feedback(self, features, feature_names, reward, truth, routing=None):
        print("DTC model send-feedback entered")
        print(f"Truth: {truth}, Reward: {reward}")

        if reward == 1:
            if truth == 1:
                self.cm["tp"] += 1
            if truth == 0:
                self.cm["tn"] += 1
        if reward == 0:
            if truth == 1:
                self.cm["fn"] += 1
            if truth == 0:
                self.cm["fp"] += 1

        self.tries += 1
        self.success = self.success + 1 if reward else self.success
        self.value = self.success / self.tries

        print(self.cm)
        print(
            "Tries: %s, successes: %s, values: %s", self.tries, self.success, self.value
        )

    def metrics(self):
        tp = {
            "type": "GAUGE",
            "key": "true_pos_total",
            "value": self.cm["tp"],
            "tags": {"branch_name": "DTC"},
        }
        tn = {
            "type": "GAUGE",
            "key": "true_neg_total",
            "value": self.cm["tn"],
            "tags": {"branch_name": "DTC"},
        }
        fp = {
            "type": "GAUGE",
            "key": "false_pos_total",
            "value": self.cm["fp"],
            "tags": {"branch_name": "DTC"},
        }
        fn = {
            "type": "GAUGE",
            "key": "false_neg_total",
            "value": self.cm["fn"],
            "tags": {"branch_name": "DTC"},
        }

        value = {
            "type": "GAUGE",
            "key": "branch_value",
            "value": self.value,
            "tags": {"branch_name": "DTC"},
        }
        success = {
            "type": "GAUGE",
            "key": "n_success_total",
            "value": self.success,
            "tags": {"branch_name": "DTC"},
        }
        tries = {
            "type": "GAUGE",
            "key": "n_tries_total",
            "value": self.tries,
            "tags": {"branch_name": "DTC"},
        }

        return [tp, tn, fp, fn, value, success, tries]

In [10]:
import pandas as pd
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.preprocessing import OrdinalEncoder

class GBCModel(object):  
    
    def __init__(self):
        
        self.categorical_features = [
            "person_home_ownership",
            "loan_intent",
            "city",
            "state",
            "location_type",
        ]
        
        self.encoder = joblib.load("encoder.pkl")
        
        print("Encoder loaded")
        
        self.model = joblib.load("GBC.pkl")
        
        print("Model loaded")

    def predict(self,X,features_names):

        df = pd.DataFrame(X, columns=features_names)
        
        df[self.categorical_features] = self.encoder.transform(df[self.categorical_features])
        df = df.reindex(sorted(df.columns), axis=1)
        
        predictions = self.model.predict(df)
        
        print(predictions)
        
        return predictions

    def send_feedback(self, features, feature_names, reward, truth, routing=None):
        print("GBC model send-feedback entered")
        print(f"Truth: {truth}, Reward: {reward}")

        if reward == 1:
            if truth == 1:
                self.cm["tp"] += 1
            if truth == 0:
                self.cm["tn"] += 1
        if reward == 0:
            if truth == 1:
                self.cm["fn"] += 1
            if truth == 0:
                self.cm["fp"] += 1

        self.tries += 1
        self.success = self.success + 1 if reward else self.success
        self.value = self.success / self.tries

        print(self.cm)
        print(
            "Tries: %s, successes: %s, values: %s", self.tries, self.success, self.value
        )

    def metrics(self):
        tp = {
            "type": "GAUGE",
            "key": "true_pos_total",
            "value": self.cm["tp"],
            "tags": {"branch_name": "GBC"},
        }
        tn = {
            "type": "GAUGE",
            "key": "true_neg_total",
            "value": self.cm["tn"],
            "tags": {"branch_name": "GBC"},
        }
        fp = {
            "type": "GAUGE",
            "key": "false_pos_total",
            "value": self.cm["fp"],
            "tags": {"branch_name": "GBC"},
        }
        fn = {
            "type": "GAUGE",
            "key": "false_neg_total",
            "value": self.cm["fn"],
            "tags": {"branch_name": "GBC"},
        }

        value = {
            "type": "GAUGE",
            "key": "branch_value",
            "value": self.value,
            "tags": {"branch_name": "GBC"},
        }
        success = {
            "type": "GAUGE",
            "key": "n_success_total",
            "value": self.success,
            "tags": {"branch_name": "GBC"},
        }
        tries = {
            "type": "GAUGE",
            "key": "n_tries_total",
            "value": self.tries,
            "tags": {"branch_name": "GBC"},
        }

        return [tp, tn, fp, fn, value, success, tries]

# Цикл тестирования

In [11]:
import joblib

dtc = DTCModel()
gbc = GBCModel()

Encoder loaded
Model loaded
Encoder loaded
Model loaded

In [12]:
import numpy as np
import requests

n = 100

for i in range(n):
    print(f"Processed {i+1}/{n} samples", flush=True)  
    
#     Локальный тест классов !!!!!!!!!!

#     print([X[i].tolist()])
#     pred = dtc.predict([X[i].tolist()], columns)
#     print(pred)
    
#     truth_val = int(y[i][0])
    
#     reward = int(pred == truth_val)
#     print(reward)
    
#     _ = dtc.send_feedback([], [], reward, truth_val)
    
#     reward = int(pred == truth_val)


#     Тест на сервере !!!!!!!!!!

    url = '' # Надо заполнить
    
    req = {"data": {"ndarray": [X[i].tolist()], "names": columns}}
    
    res_raw = requests.post(
        f"{url}/predictions", json=req
    )
    res = res_raw.json()
    
    pred = response.get("data").get("ndarray")[0]
    
    truth_val = int(y[i][0])
    
    reward = int(pred == truth_val)
    
    truth = [truth_val]
    
    feedback = {
        "request": req,
        "response": res,
        "reward": reward,
        "truth": {"data": {"ndarray": truth}}
    }
    
    res_raw = requests.post(
        f"{url}/feedback", json=feedback
    )
    assert res_raw.status_code == 200

Processed 1/100 samples
[[52, 69996, 'OWN', 3.0, 'PERSONAL', 12000, 11.11, 'CUMMINGS', 'KS', 'PRIMARY', 253, 472, 9617849, 7649, 779433, 28579, 3583, 0, 0, 0, 0, 0]]
[0]
1
DTC model send-feedback entered
Truth: 0, Reward: 1
{'tp': 0, 'fp': 0, 'tn': 1, 'fn': 0}
Tries: %s, successes: %s, values: %s 1 1 1.0
Processed 2/100 samples
[[61, 10636, 'RENT', 3.0, 'PERSONAL', 4000, 12.21, 'CRESSON', 'TX', 'PRIMARY', 703, 1342, 38291019, 5101, 1877182, 32008, 20745, 6, 1, 3, 0, 0]]
[1]
1
DTC model send-feedback entered
Truth: 1, Reward: 1
{'tp': 1, 'fp': 0, 'tn': 1, 'fn': 0}
Tries: %s, successes: %s, values: %s 2 2 1.0
Processed 3/100 samples
[[36, 69000, 'RENT', 0.0, 'MEDICAL', 15600, 10.99, 'PLAINVILLE', 'GA', 'PRIMARY', 824, 1578, 23478174, 4223, 1142978, 24020, 11711, 3, 5, 1, 1, 2]]
[0]
1
DTC model send-feedback entered
Truth: 0, Reward: 1
{'tp': 1, 'fp': 0, 'tn': 2, 'fn': 0}
Tries: %s, successes: %s, values: %s 3 3 1.0
Processed 4/100 samples
[[36, 48686, 'RENT', 21.0, 'MEDICAL', 12000, 13.99, 'CLINTON', 'NC', 'PRIMARY', 1353, 2505, 35505191, 6993, 592528, 40529, 17508, 1, 1, 0, 0, 0]]
[0]
1
DTC model send-feedback entered
Truth: 0, Reward: 1
{'tp': 1, 'fp': 0, 'tn': 3, 'fn': 0}
Tries: %s, successes: %s, values: %s 4 4 1.0
Processed 5/100 samples
[[36, 44000, 'RENT', 4.0, 'DEBTCONSOLIDATION', 8000, 17.49, 'NASHVILLE', 'TN', 'PRIMARY', 15882, 24868, 571965786, 1552, 1786677, 26664, 19749, 8, 2, 0, 1, 0]]
[1]
1
DTC model send-feedback entered
Truth: 1, Reward: 1
{'tp': 2, 'fp': 0, 'tn': 3, 'fn': 0}
Tries: %s, successes: %s, values: %s 5 5 1.0
Processed 6/100 samples
[[36, 16800, 'RENT', 2.0, 'VENTURE', 1200, 13.06, 'ENGLEWOOD', 'CO', 'PRIMARY', 10055, 16323, 317249784, 812, 383410, 24635, 11533, 4, 2, 3, 1, 0]]
[0]
1
DTC model send-feedback entered
Truth: 0, Reward: 1
{'tp': 2, 'fp': 0, 'tn': 4, 'fn': 0}
Tries: %s, successes: %s, values: %s 6 6 1.0
Processed 7/100 samples
[[41, 45840, 'RENT', 5.0, 'DEBTCONSOLIDATION', 4600, 10.99, 'CHICKASHA', 'OK', 'PRIMARY', 715, 1257, 23674694, 9392, 1340072, 7731, 2582, 0, 1, 0, 0, 0]]
[0]
1
DTC model send-feedback entered
Truth: 0, Reward: 1
{'tp': 2, 'fp': 0, 'tn': 5, 'fn': 0}
Tries: %s, successes: %s, values: %s 7 7 1.0
Processed 8/100 samples
[[56, 70000, 'MORTGAGE', 7.0, 'PERSONAL', 15000, 10.38, 'BIRMINGHAM', 'AL', 'PRIMARY', 255, 396, 8172715, 9492, 1549251, 21614, 16412, 0, 0, 0, 0, 0]]
[0]
1
DTC model send-feedback entered
Truth: 0, Reward: 1
{'tp': 2, 'fp': 0, 'tn': 6, 'fn': 0}
Tries: %s, successes: %s, values: %s 8 8 1.0
Processed 9/100 samples
[[56, 70000, 'MORTGAGE', 17.0, 'PERSONAL', 2500, 5.99, 'DRAKE', 'CO', 'PRIMARY', 348, 579, 10947330, 5086, 435576, 45768, 295, 1, 1, 0, 0, 0]]
[0]
1
DTC model send-feedback entered
Truth: 0, Reward: 1
{'tp': 2, 'fp': 0, 'tn': 7, 'fn': 0}
Tries: %s, successes: %s, values: %s 9 9 1.0
Processed 10/100 samples
[[53, 43200, 'RENT', 0.0, 'VENTURE', 10000, 9.88, 'PRINCESS ANNE', 'MD', 'PRIMARY', 3613, 6140, 103262134, 1169, 509205, 5897, 18157, 0, 7, 0, 0, 2]]
[0]
1
DTC model send-feedback entered
Truth: 0, Reward: 1
{'tp': 2, 'fp': 0, 'tn': 8, 'fn': 0}
Tries: %s, successes: %s, values: %s 10 10 1.0
Processed 11/100 samples
[[36, 60000, 'MORTGAGE', 2.0, 'VENTURE', 8000, 13.92, 'BORON', 'CA', 'PRIMARY', 720, 1337, 23917556, 6324, 1896776, 29719, 27057, 6, 3, 0, 1, 0]]
[0]
1
DTC model send-feedback entered
Truth: 0, Reward: 1
{'tp': 2, 'fp': 0, 'tn': 9, 'fn': 0}
Tries: %s, successes: %s, values: %s 11 11 1.0
Processed 12/100 samples
[[38, 99996, 'OWN', 22.0, 'MEDICAL', 25000, 14.96, 'SONOITA', 'AZ', 'PRIMARY', 687, 1225, 26050942, 9997, 680873, 12703, 9772, 0, 1, 0, 0, 0]]
[0]
1
DTC model send-feedback entered
Truth: 0, Reward: 1
{'tp': 2, 'fp': 0, 'tn': 10, 'fn': 0}
Tries: %s, successes: %s, values: %s 12 12 1.0
Processed 13/100 samples
[[36, 72000, 'MORTGAGE', 3.0, 'VENTURE', 8000, 6.92, 'BOULDER', 'CO', 'PRIMARY', 12035, 19036, 597293486, 8951, 1378486, 31016, 27745, 0, 1, 1, 0, 0]]
[0]
1
DTC model send-feedback entered
Truth: 0, Reward: 1
{'tp': 2, 'fp': 0, 'tn': 11, 'fn': 0}
Tries: %s, successes: %s, values: %s 13 13 1.0
Processed 14/100 samples
[[43, 112000, 'MORTGAGE', 14.0, 'PERSONAL', 25000, 14.96, 'NORTH TROY', 'VT', 'PRIMARY', 827, 1422, 21480484, 1089, 888007, 27079, 25485, 1, 1, 0, 0, 0]]
[0]
1
DTC model send-feedback entered
Truth: 0, Reward: 1
{'tp': 2, 'fp': 0, 'tn': 12, 'fn': 0}
Tries: %s, successes: %s, values: %s 14 14 1.0
Processed 15/100 samples
[[37, 90000, 'MORTGAGE', 11.0, 'DEBTCONSOLIDATION', 4000, 6.62, 'WALTON', 'NE', 'PRIMARY', 354, 645, 26061126, 4543, 507950, 44678, 26691, 0, 1, 0, 0, 0]]
[0]
1
DTC model send-feedback entered
Truth: 0, Reward: 1
{'tp': 2, 'fp': 0, 'tn': 13, 'fn': 0}
Tries: %s, successes: %s, values: %s 15 15 1.0
Processed 16/100 samples
[[36, 31000, 'RENT', 2.0, 'VENTURE', 2500, 8.9, 'AKRON', 'OH', 'PRIMARY', 283, 351, 4149281, 6442, 1276049, 16700, 24537, 1, 2, 3, 1, 0]]
[0]
1
DTC model send-feedback entered
Truth: 0, Reward: 1
{'tp': 2, 'fp': 0, 'tn': 14, 'fn': 0}
Tries: %s, successes: %s, values: %s 16 16 1.0
Processed 17/100 samples
[[49, 64600, 'MORTGAGE', 4.0, 'MEDICAL', 10000, 16.49, 'PIERCE CITY', 'MO', 'PRIMARY', 1563, 2885, 39822588, 2300, 1940775, 13676, 19632, 9, 0, 0, 1, 0]]
[1]
1
DTC model send-feedback entered
Truth: 1, Reward: 1
{'tp': 3, 'fp': 0, 'tn': 14, 'fn': 0}
Tries: %s, successes: %s, values: %s 17 17 1.0
Processed 18/100 samples
[[42, 600000, 'OTHER', 2.0, 'HOMEIMPROVEMENT', 25000, 14.74, 'SARASOTA', 'FL', 'PRIMARY', 8229, 13181, 188066262, 5698, 1697752, 40757, 26889, 0, 1, 0, 0, 0]]
[0]
1
DTC model send-feedback entered
Truth: 0, Reward: 1
{'tp': 3, 'fp': 0, 'tn': 15, 'fn': 0}
Tries: %s, successes: %s, values: %s 18 18 1.0
Processed 19/100 samples
[[38, 55000, 'RENT', 2.0, 'PERSONAL', 14000, 11.48, 'HEMLOCK', 'NY', 'PRIMARY', 873, 1557, 29993583, 5616, 1342615, 49539, 25021, 6, 2, 0, 0, 0]]
[0]
1
DTC model send-feedback entered
Truth: 0, Reward: 1
{'tp': 3, 'fp': 0, 'tn': 16, 'fn': 0}
Tries: %s, successes: %s, values: %s 19 19 1.0
Processed 20/100 samples
[[45, 64000, 'MORTGAGE', 3.0, 'PERSONAL', 6000, 7.29, 'ROCKY MOUNT', 'MO', 'PRIMARY', 752, 1311, 16648317, 4727, 1971535, 24825, 17764, 8, 0, 1, 0, 0]]
[0]
1
DTC model send-feedback entered
Truth: 0, Reward: 1
{'tp': 3, 'fp': 0, 'tn': 17, 'fn': 0}
Tries: %s, successes: %s, values: %s 20 20 1.0
Processed 21/100 samples
[[39, 80000, 'MORTGAGE', 18.0, 'MEDICAL', 5600, 13.43, 'VAIL', 'CO', 'PRIMARY', 2288, 3068, 98307688, 5374, 1150358, 31044, 11482, 1, 0, 0, 0, 0]]
[0]
1
DTC model send-feedback entered
Truth: 0, Reward: 1
{'tp': 3, 'fp': 0, 'tn': 18, 'fn': 0}
Tries: %s, successes: %s, values: %s 21 21 1.0
Processed 22/100 samples
[[37, 46680, 'MORTGAGE', 6.0, 'VENTURE', 8000, 15.21, 'WAYNOKA', 'OK', 'PRIMARY', 594, 1060, 15347905, 3832, 1636170, 28407, 22912, 0, 0, 0, 0, 0]]
[0]
1
DTC model send-feedback entered
Truth: 0, Reward: 1
{'tp': 3, 'fp': 0, 'tn': 19, 'fn': 0}
Tries: %s, successes: %s, values: %s 22 22 1.0
Processed 23/100 samples
[[55, 75000, 'MORTGAGE', 3.0, 'PERSONAL', 10000, 7.51, 'CLARK', 'SD', 'PRIMARY', 841, 1446, 18569304, 943, 759268, 35616, 15074, 0, 1, 0, 0, 0]]
[0]
1
DTC model send-feedback entered
Truth: 0, Reward: 1
{'tp': 3, 'fp': 0, 'tn': 20, 'fn': 0}
Tries: %s, successes: %s, values: %s 23 23 1.0
Processed 24/100 samples
[[53, 75000, 'MORTGAGE', 4.0, 'PERSONAL', 10000, 8.94, 'BEAVERTON', 'AL', 'PRIMARY', 281, 532, 7195412, 4028, 661037, 6358, 26603, 1, 1, 0, 0, 0]]
[0]
1
DTC model send-feedback entered
Truth: 0, Reward: 1
{'tp': 3, 'fp': 0, 'tn': 21, 'fn': 0}
Tries: %s, successes: %s, values: %s 24 24 1.0
Processed 25/100 samples
[[39, 40000, 'OWN', 4.0, 'VENTURE', 1000, 10.37, 'HEALDSBURG', 'CA', 'PRIMARY', 8593, 14838, 343340891, 3218, 1178912, 49863, 19306, 10, 2, 2, 0, 0]]
[0]
1
DTC model send-feedback entered
Truth: 0, Reward: 1
{'tp': 3, 'fp': 0, 'tn': 22, 'fn': 0}
Tries: %s, successes: %s, values: %s 25 25 1.0
Processed 26/100 samples
[[56, 150000, 'MORTGAGE', 5.0, 'PERSONAL', 15000, 11.48, 'DEL MAR', 'CA', 'PRIMARY', 7681, 12635, 653566215, 1257, 152136, 42087, 26234, 1, 1, 0, 0, 0]]
[0]
1
DTC model send-feedback entered
Truth: 0, Reward: 1
{'tp': 3, 'fp': 0, 'tn': 23, 'fn': 0}
Tries: %s, successes: %s, values: %s 26 26 1.0
Processed 27/100 samples

[[36, 31000, 'RENT', 2.0, 'PERSONAL', 8000, 14.11, 'DARLINGTON', 'WI', 'PRIMARY', 2196, 3993, 62007687, 2104, 677511, 15566, 12939, 8, 0, 1, 0, 0]]
[1]
1
DTC model send-feedback entered
Truth: 1, Reward: 1
{'tp': 4, 'fp': 0, 'tn': 23, 'fn': 0}
Tries: %s, successes: %s, values: %s 27 27 1.0
Processed 28/100 samples
[[36, 84996, 'MORTGAGE', 11.0, 'PERSONAL', 3500, 12.69, 'WILLIAMS', 'AZ', 'PRIMARY', 2401, 4238, 67604746, 7033, 986411, 23313, 8266, 0, 0, 0, 0, 0]]
[0]
1
DTC model send-feedback entered
Truth: 0, Reward: 1
{'tp': 4, 'fp': 0, 'tn': 24, 'fn': 0}
Tries: %s, successes: %s, values: %s 28 28 1.0
Processed 29/100 samples
[[55, 75000, 'MORTGAGE', 6.0, 'PERSONAL', 7700, 14.84, 'MENIFEE', 'CA', 'PRIMARY', 14456, 28269, 642746625, 7463, 1624026, 19352, 29641, 0, 0, 0, 0, 0]]
[0]
1
DTC model send-feedback entered
Truth: 0, Reward: 1
{'tp': 4, 'fp': 0, 'tn': 25, 'fn': 0}
Tries: %s, successes: %s, values: %s 29 29 1.0
Processed 30/100 samples
[[42, 64464, 'MORTGAGE', 13.0, 'MEDICAL', 30000, 19.03, 'BRENTON', 'WV', 'PRIMARY', 424, 822, 12015874, 6349, 1234348, 24976, 25295, 0, 4, 1, 0, 0]]
[1]
1
DTC model send-feedback entered
Truth: 1, Reward: 1
{'tp': 5, 'fp': 0, 'tn': 25, 'fn': 0}
Tries: %s, successes: %s, values: %s 30 30 1.0
Processed 31/100 samples
[[37, 50000, 'RENT', 1.0, 'DEBTCONSOLIDATION', 15000, 13.22, 'BREWSTER', 'MA', 'PRIMARY', 5179, 8575, 167998522, 8664, 920264, 47775, 23666, 10, 1, 0, 1, 0]]
[0]
1
DTC model send-feedback entered
Truth: 0, Reward: 1
{'tp': 5, 'fp': 0, 'tn': 26, 'fn': 0}
Tries: %s, successes: %s, values: %s 31 31 1.0
Processed 32/100 samples
[[46, 180000, 'MORTGAGE', 31.0, 'MEDICAL', 18000, 9.91, 'LITTLE SUAMICO', 'WI', 'PRIMARY', 1282, 2333, 58377184, 2689, 1561213, 10257, 4409, 0, 1, 0, 0, 0]]
[0]
1
DTC model send-feedback entered
Truth: 0, Reward: 1
{'tp': 5, 'fp': 0, 'tn': 27, 'fn': 0}
Tries: %s, successes: %s, values: %s 32 32 1.0
Processed 33/100 samples
[[51, 76960, 'MORTGAGE', 0.0, 'PERSONAL', 15000, 9.99, 'BELGRADE', 'ME', 'PRIMARY', 1461, 2621, 56737602, 5278, 426455, 41694, 13786, 9, 5, 1, 1, 2]]
[0]
1
DTC model send-feedback entered
Truth: 0, Reward: 1
{'tp': 5, 'fp': 0, 'tn': 28, 'fn': 0}
Tries: %s, successes: %s, values: %s 33 33 1.0
Processed 34/100 samples
[[36, 92000, 'MORTGAGE', 18.0, 'DEBTCONSOLIDATION', 4000, 7.29, 'COBB', 'CA', 'PRIMARY', 982, 1723, 39078743, 69, 385936, 9957, 25645, 0, 1, 0, 0, 0]]
[0]
1
DTC model send-feedback entered
Truth: 0, Reward: 1
{'tp': 5, 'fp': 0, 'tn': 29, 'fn': 0}
Tries: %s, successes: %s, values: %s 34 34 1.0
Processed 35/100 samples
[[52, 36000, 'RENT', 8.0, 'DEBTCONSOLIDATION', 11200, 12.18, 'BALTIMORE', 'MD', 'PRIMARY', 5709, 9645, 119290463, 4003, 1806767, 16013, 4896, 0, 3, 0, 1, 0]]
[1]
1
DTC model send-feedback entered
Truth: 1, Reward: 1
{'tp': 6, 'fp': 0, 'tn': 29, 'fn': 0}
Tries: %s, successes: %s, values: %s 35 35 1.0
Processed 36/100 samples
[[40, 52000, 'RENT', 2.0, 'EDUCATION', 15000, 18.62, 'VAN ALSTYNE', 'TX', 'PRIMARY', 3079, 5941, 144976961, 5346, 472160, 42234, 19831, 8, 7, 1, 0, 0]]
[1]
1
DTC model send-feedback entered
Truth: 1, Reward: 1
{'tp': 7, 'fp': 0, 'tn': 29, 'fn': 0}
Tries: %s, successes: %s, values: %s 36 36 1.0
Processed 37/100 samples
[[48, 66000, 'RENT', 6.0, 'HOMEIMPROVEMENT', 6000, 11.89, 'ASCUTNEY', 'VT', 'PRIMARY', 407, 676, 12613614, 6927, 1367570, 22405, 27999, 1, 0, 0, 0, 0]]
[0]
1
DTC model send-feedback entered
Truth: 0, Reward: 1
{'tp': 7, 'fp': 0, 'tn': 30, 'fn': 0}
Tries: %s, successes: %s, values: %s 37 37 1.0
Processed 38/100 samples
[[61, 90000, 'RENT', 1.0, 'MEDICAL', 10000, 5.79, 'LOS ANGELES', 'CA', 'PRIMARY', 13672, 18687, 379215740, 4799, 1272003, 23475, 26805, 6, 1, 3, 1, 0]]
[0]
1
DTC model send-feedback entered
Truth: 0, Reward: 1
{'tp': 7, 'fp': 0, 'tn': 31, 'fn': 0}
Tries: %s, successes: %s, values: %s 38 38 1.0
Processed 39/100 samples
[[41, 24000, 'RENT', 2.0, 'MEDICAL', 4000, 16.07, 'BETHANY BEACH', 'DE', 'PRIMARY', 1446, 2321, 40408105, 9622, 932893, 31685, 15486, 9, 0, 1, 0, 0]]
[1]
1
DTC model send-feedback entered
Truth: 1, Reward: 1
{'tp': 8, 'fp': 0, 'tn': 31, 'fn': 0}
Tries: %s, successes: %s, values: %s 39 39 1.0
Processed 40/100 samples
[[37, 21600, 'RENT', 7.0, 'MEDICAL', 3000, 12.18, 'TRANSFER', 'PA', 'PRIMARY', 1323, 2363, 41883271, 1753, 91728, 26217, 1213, 3, 7, 1, 1, 0]]
[0]
1
DTC model send-feedback entered
Truth: 0, Reward: 1
{'tp': 8, 'fp': 0, 'tn': 32, 'fn': 0}
Tries: %s, successes: %s, values: %s 40 40 1.0
Processed 41/100 samples
[[44, 61000, 'RENT', 2.0, 'DEBTCONSOLIDATION', 11000, 16.02, 'TANGERINE', 'FL', 'PRIMARY', 281, 509, 8962046, 9604, 1315177, 26522, 28010, 3, 3, 0, 1, 0]]
[1]
1
DTC model send-feedback entered
Truth: 1, Reward: 1
{'tp': 9, 'fp': 0, 'tn': 32, 'fn': 0}
Tries: %s, successes: %s, values: %s 41 41 1.0
Processed 42/100 samples
[[38, 110000, 'MORTGAGE', 5.0, 'MEDICAL', 16000, 11.99, 'BAY SAINT LOUIS', 'MS', 'PRIMARY', 685, 1069, 17610486, 1712, 1362639, 9225, 16356, 1, 1, 0, 0, 0]]
[0]
1
DTC model send-feedback entered
Truth: 0, Reward: 1
{'tp': 9, 'fp': 0, 'tn': 33, 'fn': 0}
Tries: %s, successes: %s, values: %s 42 42 1.0
Processed 43/100 samples
[[60, 72000, 'OWN', 3.0, 'PERSONAL', 10000, 10.59, 'PETROS', 'TN', 'PRIMARY', 254, 485, 6441149, 4078, 999563, 16812, 14182, 1, 0, 0, 0, 0]]
[0]
1
DTC model send-feedback entered
Truth: 0, Reward: 1
{'tp': 9, 'fp': 0, 'tn': 34, 'fn': 0}
Tries: %s, successes: %s, values: %s 43 43 1.0
Processed 44/100 samples
[[42, 32000, 'RENT', 5.0, 'DEBTCONSOLIDATION', 10000, 11.71, 'MIAMI', 'FL', 'PRIMARY', 6709, 10362, 406454295, 1624, 317054, 20207, 19389, 5, 6, 1, 0, 0]]
[1]
1
DTC model send-feedback entered
Truth: 1, Reward: 1
{'tp': 10, 'fp': 0, 'tn': 34, 'fn': 0}
Tries: %s, successes: %s, values: %s 44 44 1.0
Processed 45/100 samples
[[56, 59200, 'RENT', 1.0, 'DEBTCONSOLIDATION', 10000, 13.61, 'GILBERT', 'AZ', 'PRIMARY', 6820, 13876, 436276795, 5656, 1537653, 37419, 11610, 8, 4, 2, 0, 0]]
[0]
1
DTC model send-feedback entered
Truth: 0, Reward: 1
{'tp': 10, 'fp': 0, 'tn': 35, 'fn': 0}
Tries: %s, successes: %s, values: %s 45 45 1.0
Processed 46/100 samples
[[38, 40000, 'MORTGAGE', 5.0, 'PERSONAL', 10000, 5.99, 'VIRGINIA BEACH', 'VA', 'PRIMARY', 21485, 33789, 996277136, 8211, 1094075, 39429, 182, 7, 0, 1, 1, 0]]
[0]
1
DTC model send-feedback entered
Truth: 0, Reward: 1
{'tp': 10, 'fp': 0, 'tn': 36, 'fn': 0}
Tries: %s, successes: %s, values: %s 46 46 1.0
Processed 47/100 samples
[[36, 145000, 'MORTGAGE', 4.0, 'DEBTCONSOLIDATION', 5000, 9.62, 'MAYSVILLE', 'WV', 'PRIMARY', 915, 1715, 26302665, 9805, 1906988, 872, 1091, 1, 0, 0, 0, 0]]
[0]
1
DTC model send-feedback entered
Truth: 0, Reward: 1
{'tp': 10, 'fp': 0, 'tn': 37, 'fn': 0}
Tries: %s, successes: %s, values: %s 47 47 1.0
Processed 48/100 samples
[[56, 71884, 'OWN', 11.0, 'PERSONAL', 7425, 9.99, 'TYLER', 'AL', 'PRIMARY', 562, 1044, 13717069, 4849, 1381850, 41375, 6019, 1, 0, 0, 0, 0]]
[0]
1
DTC model send-feedback entered
Truth: 0, Reward: 1
{'tp': 10, 'fp': 0, 'tn': 38, 'fn': 0}
Tries: %s, successes: %s, values: %s 48 48 1.0
Processed 49/100 samples
[[36, 53800, 'MORTGAGE', 20.0, 'DEBTCONSOLIDATION', 18200, 18.25, 'NICOLLET', 'MN', 'PRIMARY', 995, 1798, 31695489, 4095, 42526, 13544, 19905, 0, 6, 0, 1, 0]]
[1]
1
DTC model send-feedback entered
Truth: 1, Reward: 1
{'tp': 11, 'fp': 0, 'tn': 38, 'fn': 0}
Tries: %s, successes: %s, values: %s 49 49 1.0
Processed 50/100 samples
[[41, 24000, 'OWN', 3.0, 'EDUCATION', 4500, 12.99, 'PIRU', 'CA', 'PRIMARY', 841, 1683, 26539004, 865, 401602, 48206, 8348, 2, 2, 0, 1, 0]]
[0]
1
DTC model send-feedback entered
Truth: 0, Reward: 1
{'tp': 11, 'fp': 0, 'tn': 39, 'fn': 0}
Tries: %s, successes: %s, values: %s 50 50 1.0
Processed 51/100 samples
[[36, 24000, 'MORTGAGE', 2.0, 'MEDICAL', 1500, 9.63, 'COSHOCTON', 'OH', 'PRIMARY', 8965, 15393, 240178803, 6267, 506043, 2880, 28533, 8, 7, 2, 1, 0]]
[0]
1
DTC model send-feedback entered
Truth: 0, Reward: 1
{'tp': 11, 'fp': 0, 'tn': 40, 'fn': 0}
Tries: %s, successes: %s, values: %s 51 51 1.0
Processed 52/100 samples
[[37, 42000, 'RENT', 2.0, 'MEDICAL', 8400, 13.49, 'BOYNTON', 'OK', 'PRIMARY', 318, 607, 9696906, 8818, 675447, 49775, 19768, 10, 3, 3, 1, 0]]
[0]
1
DTC model send-feedback entered
Truth: 0, Reward: 1
{'tp': 11, 'fp': 0, 'tn': 41, 'fn': 0}
Tries: %s, successes: %s, values: %s 52 52 1.0
Processed 53/100 samples

[[46, 60000, 'RENT', 9.0, 'HOMEIMPROVEMENT', 15000, 16.32, 'HICKMAN', 'KY', 'PRIMARY', 1170, 2108, 24786335, 7488, 1680839, 43147, 17194, 0, 1, 0, 0, 0]]
[0]
1
DTC model send-feedback entered
Truth: 0, Reward: 1
{'tp': 11, 'fp': 0, 'tn': 42, 'fn': 0}
Tries: %s, successes: %s, values: %s 53 53 1.0
Processed 54/100 samples
[[42, 50426, 'RENT', 0.0, 'MEDICAL', 4200, 7.49, 'FOSS', 'OK', 'PRIMARY', 321, 595, 10017823, 2395, 269401, 31834, 18682, 9, 6, 0, 0, 2]]
[0]
1
DTC model send-feedback entered
Truth: 0, Reward: 1
{'tp': 11, 'fp': 0, 'tn': 43, 'fn': 0}
Tries: %s, successes: %s, values: %s 54 54 1.0
Processed 55/100 samples
[[38, 30000, 'MORTGAGE', 8.0, 'HOMEIMPROVEMENT', 10000, 11.22, 'BRANDON', 'MN', 'PRIMARY', 745, 1355, 23203616, 870, 555643, 3781, 10059, 4, 6, 1, 0, 0]]
[0]
1
DTC model send-feedback entered
Truth: 0, Reward: 1
{'tp': 11, 'fp': 0, 'tn': 44, 'fn': 0}
Tries: %s, successes: %s, values: %s 55 55 1.0
Processed 56/100 samples
[[41, 90000, 'MORTGAGE', 3.0, 'PERSONAL', 3000, 7.14, 'ANKENY', 'IA', 'PRIMARY', 12076, 22710, 689066606, 7800, 901262, 9971, 28623, 1, 1, 0, 0, 0]]
[0]
1
DTC model send-feedback entered
Truth: 0, Reward: 1
{'tp': 11, 'fp': 0, 'tn': 45, 'fn': 0}
Tries: %s, successes: %s, values: %s 56 56 1.0
Processed 57/100 samples
[[51, 74628, 'MORTGAGE', 3.0, 'PERSONAL', 3000, 13.49, 'HUNTINGTON BEACH', 'CA', 'PRIMARY', 513, 746, 19749601, 3679, 1659968, 37582, 20284, 0, 1, 0, 0, 0]]
[0]
1
DTC model send-feedback entered
Truth: 0, Reward: 1
{'tp': 11, 'fp': 0, 'tn': 46, 'fn': 0}
Tries: %s, successes: %s, values: %s 57 57 1.0
Processed 58/100 samples
[[37, 32000, 'RENT', 4.0, 'MEDICAL', 10000, 13.79, 'NEW CANTON', 'IL', 'PRIMARY', 270, 478, 7369943, 8973, 1172483, 44362, 3673, 4, 2, 2, 0, 0]]
[1]
1
DTC model send-feedback entered
Truth: 1, Reward: 1
{'tp': 12, 'fp': 0, 'tn': 46, 'fn': 0}
Tries: %s, successes: %s, values: %s 58 58 1.0
Processed 59/100 samples
[[64, 56000, 'RENT', 0.0, 'DEBTCONSOLIDATION', 10000, 16.82, 'SPRINGFIELD', 'MO', 'PRIMARY', 3533, 4884, 59028597, 1698, 182772, 11127, 8693, 1, 6, 0, 0, 1]]
[1]
1
DTC model send-feedback entered
Truth: 1, Reward: 1
{'tp': 13, 'fp': 0, 'tn': 46, 'fn': 0}
Tries: %s, successes: %s, values: %s 59 59 1.0
Processed 60/100 samples
[[39, 150000, 'MORTGAGE', 9.0, 'MEDICAL', 30000, 8.9, 'LYMAN', 'NE', 'PRIMARY', 285, 529, 7532319, 9542, 1170659, 2384, 28421, 0, 0, 0, 0, 0]]
[0]
1
DTC model send-feedback entered
Truth: 0, Reward: 1
{'tp': 13, 'fp': 0, 'tn': 47, 'fn': 0}
Tries: %s, successes: %s, values: %s 60 60 1.0
Processed 61/100 samples
[[40, 43000, 'MORTGAGE', 18.0, 'PERSONAL', 2500, 12.84, 'PORT SULPHUR', 'LA', 'PRIMARY', 1045, 1803, 29942197, 1351, 1651520, 36461, 11056, 0, 0, 0, 0, 0]]
[0]
1
DTC model send-feedback entered
Truth: 0, Reward: 1
{'tp': 13, 'fp': 0, 'tn': 48, 'fn': 0}
Tries: %s, successes: %s, values: %s 61 61 1.0
Processed 62/100 samples
[[36, 15000, 'OWN', 2.0, 'HOMEIMPROVEMENT', 5000, 13.92, 'NEW HILL', 'NC', 'PRIMARY', 846, 1553, 38248681, 7956, 1141491, 35441, 4731, 5, 7, 3, 0, 2]]
[1]
1
DTC model send-feedback entered
Truth: 1, Reward: 1
{'tp': 14, 'fp': 0, 'tn': 48, 'fn': 0}
Tries: %s, successes: %s, values: %s 62 62 1.0
Processed 63/100 samples
[[55, 34000, 'RENT', 0.0, 'DEBTCONSOLIDATION', 12000, 6.92, 'SANTA BARBARA', 'CA', 'PRIMARY', 602, 909, 24537583, 8091, 364271, 30248, 22640, 2, 7, 3, 0, 0]]
[1]
1
DTC model send-feedback entered
Truth: 1, Reward: 1
{'tp': 15, 'fp': 0, 'tn': 48, 'fn': 0}
Tries: %s, successes: %s, values: %s 63 63 1.0
Processed 64/100 samples
[[45, 60000, 'RENT', 4.0, 'EDUCATION', 25000, 9.99, 'MORRILL', 'NE', 'PRIMARY', 908, 1617, 27166691, 8302, 440950, 12761, 8843, 7, 4, 3, 1, 0]]
[1]
1
DTC model send-feedback entered
Truth: 1, Reward: 1
{'tp': 16, 'fp': 0, 'tn': 48, 'fn': 0}
Tries: %s, successes: %s, values: %s 64 64 1.0
Processed 65/100 samples
[[38, 200000, 'MORTGAGE', 0.0, 'DEBTCONSOLIDATION', 3000, 7.68, 'PORT SAINT JOE', 'FL', 'PRIMARY', 427, 718, 11062523, 798, 494669, 3673, 511, 9, 5, 1, 1, 1]]
[0]
1
DTC model send-feedback entered
Truth: 0, Reward: 1
{'tp': 16, 'fp': 0, 'tn': 49, 'fn': 0}
Tries: %s, successes: %s, values: %s 65 65 1.0
Processed 66/100 samples
[[38, 20640, 'RENT', 2.0, 'DEBTCONSOLIDATION', 3500, 12.61, 'EATONTON', 'GA', 'PRIMARY', 8766, 15971, 252689868, 4792, 1287814, 10647, 18888, 9, 4, 2, 0, 0]]
[0]
1
DTC model send-feedback entered
Truth: 0, Reward: 1
{'tp': 16, 'fp': 0, 'tn': 50, 'fn': 0}
Tries: %s, successes: %s, values: %s 66 66 1.0
Processed 67/100 samples
[[65, 93000, 'MORTGAGE', 27.0, 'PERSONAL', 25000, 9.99, 'MONGAUP VALLEY', 'NY', 'PRIMARY', 275, 460, 8417447, 6002, 1840255, 10216, 19616, 0, 1, 0, 0, 0]]
[0]
1
DTC model send-feedback entered
Truth: 0, Reward: 1
{'tp': 16, 'fp': 0, 'tn': 51, 'fn': 0}
Tries: %s, successes: %s, values: %s 67 67 1.0
Processed 68/100 samples
[[55, 91154, 'MORTGAGE', 15.0, 'PERSONAL', 10000, 6.62, 'CONYNGHAM', 'PA', 'PRIMARY', 927, 1540, 32488684, 2404, 506620, 29036, 5017, 0, 0, 0, 0, 0]]
[0]
1
DTC model send-feedback entered
Truth: 0, Reward: 1
{'tp': 16, 'fp': 0, 'tn': 52, 'fn': 0}
Tries: %s, successes: %s, values: %s 68 68 1.0
Processed 69/100 samples
[[48, 140000, 'MORTGAGE', 4.0, 'EDUCATION', 18000, 9.99, 'OSHKOSH', 'WI', 'PRIMARY', 15059, 23996, 469695341, 48, 1454913, 39955, 1506, 1, 1, 0, 0, 0]]
[0]
1
DTC model send-feedback entered
Truth: 0, Reward: 1
{'tp': 16, 'fp': 0, 'tn': 53, 'fn': 0}
Tries: %s, successes: %s, values: %s 69 69 1.0
Processed 70/100 samples
[[64, 24000, 'RENT', 1.0, 'MEDICAL', 3000, 6.99, 'BISMARCK', 'ND', 'PRIMARY', 11564, 19832, 469621263, 5917, 1780959, 11835, 27910, 8, 3, 2, 1, 0]]
[0]
1
DTC model send-feedback entered
Truth: 0, Reward: 1
{'tp': 16, 'fp': 0, 'tn': 54, 'fn': 0}
Tries: %s, successes: %s, values: %s 70 70 1.0
Processed 71/100 samples
[[62, 16800, 'RENT', 0.0, 'VENTURE', 2500, 6.91, 'CHERRY VALLEY', 'MA', 'PRIMARY', 1047, 1777, 40897361, 7788, 507646, 14093, 11344, 8, 6, 2, 0, 2]]
[0]
1
DTC model send-feedback entered
Truth: 0, Reward: 1
{'tp': 16, 'fp': 0, 'tn': 55, 'fn': 0}
Tries: %s, successes: %s, values: %s 71 71 1.0
Processed 72/100 samples
[[51, 68000, 'RENT', 5.0, 'PERSONAL', 12000, 16.77, 'CALEDONIA', 'OH', 'PRIMARY', 1475, 2603, 47618321, 4016, 1354284, 5796, 10927, 0, 1, 0, 0, 0]]
[0]
1
DTC model send-feedback entered
Truth: 0, Reward: 1
{'tp': 16, 'fp': 0, 'tn': 56, 'fn': 0}
Tries: %s, successes: %s, values: %s 72 72 1.0
Processed 73/100 samples
[[38, 18000, 'RENT', 4.0, 'PERSONAL', 3000, 13.23, 'LANAI CITY', 'HI', 'PRIMARY', 1482, 2595, 54572310, 9947, 983103, 30321, 2855, 3, 4, 0, 1, 0]]
[1]
1
DTC model send-feedback entered
Truth: 1, Reward: 1
{'tp': 17, 'fp': 0, 'tn': 56, 'fn': 0}
Tries: %s, successes: %s, values: %s 73 73 1.0
Processed 74/100 samples
[[54, 95000, 'MORTGAGE', 3.0, 'PERSONAL', 6500, 10.65, 'GREENSBORO', 'NC', 'PRIMARY', 305, 470, 9289521, 4215, 1350709, 36920, 18452, 1, 1, 0, 0, 0]]
[0]
1
DTC model send-feedback entered
Truth: 0, Reward: 1
{'tp': 17, 'fp': 0, 'tn': 57, 'fn': 0}
Tries: %s, successes: %s, values: %s 74 74 1.0
Processed 75/100 samples
[[64, 105000, 'RENT', 8.0, 'HOMEIMPROVEMENT', 20000, 18.64, 'LUMBERTON', 'NC', 'PRIMARY', 4382, 8229, 114279904, 7883, 961731, 49566, 12443, 1, 0, 0, 0, 0]]
[0]
1
DTC model send-feedback entered
Truth: 0, Reward: 1
{'tp': 17, 'fp': 0, 'tn': 58, 'fn': 0}
Tries: %s, successes: %s, values: %s 75 75 1.0
Processed 76/100 samples
[[49, 120000, 'MORTGAGE', 12.0, 'MEDICAL', 12000, 10.99, 'PLEASANT HILL', 'OH', 'PRIMARY', 962, 1723, 31491311, 1202, 301870, 40207, 29783, 1, 1, 0, 0, 0]]
[0]
1
DTC model send-feedback entered
Truth: 0, Reward: 1
{'tp': 17, 'fp': 0, 'tn': 59, 'fn': 0}
Tries: %s, successes: %s, values: %s 76 76 1.0
Processed 77/100 samples
[[53, 95000, 'OWN', 24.0, 'PERSONAL', 6000, 5.42, 'MONTROSE', 'AL', 'PRIMARY', 524, 938, 29158961, 7153, 200320, 11270, 6070, 1, 1, 0, 0, 0]]
[0]
1
DTC model send-feedback entered
Truth: 0, Reward: 1
{'tp': 17, 'fp': 0, 'tn': 60, 'fn': 0}
Tries: %s, successes: %s, values: %s 77 77 1.0
Processed 78/100 samples
[[39, 75000, 'RENT', 0.0, 'PERSONAL', 14400, 12.53, 'NEPONSET', 'IL', 'PRIMARY', 413, 730, 11569469, 6758, 1809411, 46992, 3564, 5, 6, 1, 0, 0]]
[0]
1
DTC model send-feedback entered
Truth: 0, Reward: 1
{'tp': 17, 'fp': 0, 'tn': 61, 'fn': 0}
Tries: %s, successes: %s, values: %s 78 78 1.0
Processed 79/100 samples

[[55, 94000, 'MORTGAGE', 11.0, 'PERSONAL', 4000, 6.62, 'FAIRCHANCE', 'PA', 'PRIMARY', 1267, 2180, 33272489, 7044, 370857, 24474, 7277, 1, 1, 0, 0, 0]]
[0]
1
DTC model send-feedback entered
Truth: 0, Reward: 1
{'tp': 17, 'fp': 0, 'tn': 62, 'fn': 0}
Tries: %s, successes: %s, values: %s 79 79 1.0
Processed 80/100 samples
[[41, 52106, 'RENT', 4.0, 'EDUCATION', 5000, 12.84, 'WEST DOVER', 'VT', 'PRIMARY', 687, 1043, 16848829, 6505, 1717133, 31418, 23388, 2, 2, 2, 0, 0]]
[1]
1
DTC model send-feedback entered
Truth: 1, Reward: 1
{'tp': 18, 'fp': 0, 'tn': 62, 'fn': 0}
Tries: %s, successes: %s, values: %s 80 80 1.0
Processed 81/100 samples
[[84, 94800, 'MORTGAGE', 2.0, 'PERSONAL', 10000, 7.51, 'HAYDEN', 'AL', 'PRIMARY', 3410, 6765, 129851527, 3399, 1984292, 11697, 10166, 0, 1, 0, 0, 0]]
[0]
1
DTC model send-feedback entered
Truth: 0, Reward: 1
{'tp': 18, 'fp': 0, 'tn': 63, 'fn': 0}
Tries: %s, successes: %s, values: %s 81 81 1.0
Processed 82/100 samples
[[53, 105000, 'RENT', 1.0, 'EDUCATION', 12000, 6.91, 'CARTWRIGHT', 'OK', 'PRIMARY', 518, 959, 10922103, 3317, 1627919, 17852, 29101, 7, 6, 2, 0, 0]]
[0]
1
DTC model send-feedback entered
Truth: 0, Reward: 1
{'tp': 18, 'fp': 0, 'tn': 64, 'fn': 0}
Tries: %s, successes: %s, values: %s 82 82 1.0
Processed 83/100 samples
[[63, 1782000, 'RENT', 13.0, 'EDUCATION', 12025, 14.27, 'RENO', 'OH', 'PRIMARY', 352, 599, 9175849, 9531, 771261, 1837, 29230, 1, 1, 0, 0, 0]]
[0]
1
DTC model send-feedback entered
Truth: 0, Reward: 1
{'tp': 18, 'fp': 0, 'tn': 65, 'fn': 0}
Tries: %s, successes: %s, values: %s 83 83 1.0
Processed 84/100 samples
[[51, 80000, 'RENT', 1.0, 'HOMEIMPROVEMENT', 12000, 12.69, 'MIAMI', 'FL', 'PRIMARY', 329, 478, 9209211, 8006, 1687, 476, 6638, 9, 5, 3, 1, 0]]
[0]
1
DTC model send-feedback entered
Truth: 0, Reward: 1
{'tp': 18, 'fp': 0, 'tn': 66, 'fn': 0}
Tries: %s, successes: %s, values: %s 84 84 1.0
Processed 85/100 samples
[[64, 87000, 'MORTGAGE', 12.0, 'PERSONAL', 15000, 7.51, 'CUMBERLAND', 'KY', 'PRIMARY', 1261, 2396, 34041582, 1842, 568650, 2314, 17708, 0, 0, 0, 0, 0]]
[0]
1
DTC model send-feedback entered
Truth: 0, Reward: 1
{'tp': 18, 'fp': 0, 'tn': 67, 'fn': 0}
Tries: %s, successes: %s, values: %s 85 85 1.0
Processed 86/100 samples
[[58, 100000, 'RENT', 6.0, 'EDUCATION', 12000, 8.9, 'HAZEL', 'KY', 'PRIMARY', 681, 1257, 16178859, 7975, 194506, 32614, 10385, 1, 0, 0, 0, 0]]
[0]
1
DTC model send-feedback entered
Truth: 0, Reward: 1
{'tp': 18, 'fp': 0, 'tn': 68, 'fn': 0}
Tries: %s, successes: %s, values: %s 86 86 1.0
Processed 87/100 samples
[[51, 84000, 'RENT', 7.0, 'HOMEIMPROVEMENT', 12000, 7.49, 'HUBBARD', 'OH', 'PRIMARY', 7778, 13005, 238656592, 9122, 1747755, 48430, 22134, 0, 0, 0, 0, 0]]
[0]
1
DTC model send-feedback entered
Truth: 0, Reward: 1
{'tp': 18, 'fp': 0, 'tn': 69, 'fn': 0}
Tries: %s, successes: %s, values: %s 87 87 1.0
Processed 88/100 samples
[[61, 85000, 'MORTGAGE', 11.0, 'PERSONAL', 9000, 9.99, 'WALES', 'MA', 'PRIMARY', 850, 1491, 33870007, 6221, 1492661, 37808, 10846, 0, 0, 0, 0, 0]]
[0]
1
DTC model send-feedback entered
Truth: 0, Reward: 1
{'tp': 18, 'fp': 0, 'tn': 70, 'fn': 0}
Tries: %s, successes: %s, values: %s 88 88 1.0
Processed 89/100 samples
[[53, 92000, 'MORTGAGE', 7.0, 'PERSONAL', 15000, 11.12, 'IONIA', 'MI', 'PRIMARY', 6721, 12086, 192867778, 1606, 349936, 27205, 26185, 0, 0, 0, 0, 0]]
[0]
1
DTC model send-feedback entered
Truth: 0, Reward: 1
{'tp': 18, 'fp': 0, 'tn': 71, 'fn': 0}
Tries: %s, successes: %s, values: %s 89 89 1.0
Processed 90/100 samples
[[61, 78000, 'MORTGAGE', 1.0, 'PERSONAL', 8525, 14.54, 'DAYTON', 'OH', 'PRIMARY', 4917, 7893, 130635763, 8367, 1409877, 48827, 3738, 0, 0, 1, 1, 0]]
[1]
1
DTC model send-feedback entered
Truth: 1, Reward: 1
{'tp': 19, 'fp': 0, 'tn': 71, 'fn': 0}
Tries: %s, successes: %s, values: %s 90 90 1.0
Processed 91/100 samples
[[56, 90000, 'MORTGAGE', 0.0, 'PERSONAL', 7200, 6.17, 'BAGDAD', 'FL', 'PRIMARY', 319, 532, 7634682, 4560, 1777266, 35984, 18096, 7, 5, 1, 1, 2]]
[0]
1
DTC model send-feedback entered
Truth: 0, Reward: 1
{'tp': 19, 'fp': 0, 'tn': 72, 'fn': 0}
Tries: %s, successes: %s, values: %s 91 91 1.0
Processed 92/100 samples
[[58, 85000, 'MORTGAGE', 0.0, 'PERSONAL', 8000, 11.49, 'MARION', 'PA', 'PRIMARY', 349, 596, 10153044, 495, 1813681, 36361, 27469, 1, 4, 3, 1, 1]]
[0]
1
DTC model send-feedback entered
Truth: 0, Reward: 1
{'tp': 19, 'fp': 0, 'tn': 73, 'fn': 0}
Tries: %s, successes: %s, values: %s 92 92 1.0
Processed 93/100 samples
[[36, 32004, 'RENT', 3.0, 'MEDICAL', 5000, 10.62, 'ATHENS', 'NY', 'PRIMARY', 1623, 2840, 68064295, 7349, 142161, 31215, 22623, 6, 6, 2, 0, 0]]
[0]
1
DTC model send-feedback entered
Truth: 0, Reward: 1
{'tp': 19, 'fp': 0, 'tn': 74, 'fn': 0}
Tries: %s, successes: %s, values: %s 93 93 1.0
Processed 94/100 samples
[[36, 98240, 'MORTGAGE', 4.0, 'VENTURE', 20000, 16.35, 'FORT PIERCE', 'FL', 'PRIMARY', 10404, 18125, 279794669, 2082, 270771, 18103, 12466, 0, 0, 0, 0, 0]]
[0]
1
DTC model send-feedback entered
Truth: 0, Reward: 1
{'tp': 19, 'fp': 0, 'tn': 75, 'fn': 0}
Tries: %s, successes: %s, values: %s 94 94 1.0
Processed 95/100 samples
[[51, 72800, 'MORTGAGE', 0.0, 'PERSONAL', 5700, 7.66, 'KEYSVILLE', 'VA', 'PRIMARY', 1906, 3385, 50517233, 2376, 1722954, 22808, 4646, 3, 0, 0, 1, 2]]
[0]
1
DTC model send-feedback entered
Truth: 0, Reward: 1
{'tp': 19, 'fp': 0, 'tn': 76, 'fn': 0}
Tries: %s, successes: %s, values: %s 95 95 1.0
Processed 96/100 samples
[[59, 42000, 'RENT', 14.0, 'PERSONAL', 9600, 7.66, 'GIVEN', 'WV', 'PRIMARY', 386, 763, 16392130, 5075, 79706, 1838, 12834, 0, 0, 0, 0, 0]]
[0]
1
DTC model send-feedback entered
Truth: 0, Reward: 1
{'tp': 19, 'fp': 0, 'tn': 77, 'fn': 0}
Tries: %s, successes: %s, values: %s 96 96 1.0
Processed 97/100 samples
[[46, 88400, 'MORTGAGE', 1.0, 'MEDICAL', 30000, 18.39, 'MORIAH', 'NY', 'PRIMARY', 502, 905, 17331088, 1022, 1735858, 12131, 5257, 8, 1, 0, 0, 0]]
[1]
1
DTC model send-feedback entered
Truth: 1, Reward: 1
{'tp': 20, 'fp': 0, 'tn': 77, 'fn': 0}
Tries: %s, successes: %s, values: %s 97 97 1.0
Processed 98/100 samples
[[37, 30000, 'RENT', 7.0, 'PERSONAL', 10000, 9.25, 'MYRTLE BEACH', 'SC', 'PRIMARY', 14282, 24336, 463007727, 437, 1899460, 42260, 22283, 2, 0, 1, 1, 0]]
[1]
1
DTC model send-feedback entered
Truth: 1, Reward: 1
{'tp': 21, 'fp': 0, 'tn': 77, 'fn': 0}
Tries: %s, successes: %s, values: %s 98 98 1.0
Processed 99/100 samples
[[41, 56004, 'RENT', 4.0, 'VENTURE', 12800, 11.48, 'CRESTED BUTTE', 'CO', 'PRIMARY', 2276, 3512, 70861082, 7658, 198204, 6368, 11186, 6, 7, 3, 1, 0]]
[0]
1
DTC model send-feedback entered
Truth: 0, Reward: 1
{'tp': 21, 'fp': 0, 'tn': 78, 'fn': 0}
Tries: %s, successes: %s, values: %s 99 99 1.0
Processed 100/100 samples
[[52, 29000, 'OWN', 23.0, 'PERSONAL', 7000, 7.49, 'SAN JOSE', 'CA', 'PRIMARY', 21510, 39234, 1515281029, 6084, 1544083, 45914, 3313, 1, 0, 0, 0, 0]]
[0]
1
DTC model send-feedback entered
Truth: 0, Reward: 1
{'tp': 21, 'fp': 0, 'tn': 79, 'fn': 0}
Tries: %s, successes: %s, values: %s 100 100 1.0